# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
