# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
