# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_task_task_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('project', 'task_number')]),
        ),
    ]
