# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='compensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Compensation'),
        ),
    ]
