# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('project', '0002_projectcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dashboard',
        ),
        migrations.AddField(
            model_name='project',
            name='client_dashboard',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='dashboard.Dashboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='freelancer_dashboard',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='dashboard.Dashboard'),
            preserve_default=False,
        ),
    ]
