# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_freelancer_skills'),
        ('project', '0003_auto_20171113_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.Client'),
        ),
    ]
