# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171128_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensation',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='compensation',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.Compensation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='client_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='dashboard.Dashboard'),
        ),
        migrations.AlterField(
            model_name='project',
            name='freelancer_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='dashboard.Dashboard'),
        ),
    ]
