# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workapplication',
            name='message',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='message',
            field=models.CharField(default=b'', max_length=2000),
        ),
        migrations.AlterField(
            model_name='workoffer',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.WorkApplication'),
        ),
    ]
