# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20171116_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workapplication',
            old_name='is_accepted',
            new_name='is_declined',
        ),
        migrations.RenameField(
            model_name='workrequest',
            old_name='is_accepted',
            new_name='is_declined',
        ),
        migrations.AddField(
            model_name='workoffer',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationdetail',
            name='message',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
